behaviors:
  RigidPlanner:
    trainer_type: ppo
    max_steps: 5000000
    time_horizon: 64
    summary_freq: 50000
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 5.0e-4
      beta: 5.0e-4
      epsilon: 0.25
      lambd: 0.95
      num_epoch: 3
    network_settings:
      hidden_units: 128
      memory_size: 256
      normalize: false
      num_layers: 5
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 0.1
    behavioral_cloning:
      demo_path: Assets\Demonstrations\HighStart11
      strength: 0.5
      steps: 5000000
      curiosity:
        strength: 0.01
environment_parameters:
  pos:
    curriculum:
      - name: Lesson0
        completion_criteria:
          measure: reward
          signal_smoothing: true
          min_lesson_length: 20
          behavior: Planner
          threshold: 0.5
        value: 250
      - name: Lesson1
        completion_criteria:
          measure: reward
          signal_smoothing: true
          min_lesson_length: 20
          behavior: Planner
          threshold: 0.5
        value: 235