behaviors:
  Planner:
    trainer_type: ppo
    max_steps: 4000000
    time_horizon: 64
    summary_freq: 10000
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 5.0e-4
      beta: 5.0e-4
      epsilon: 0.25
      lambd: 0.95
      num_epoch: 3
    network_settings:
      hidden_units: 128
      memory_size: 256
      normalize: false
      num_layers: 5
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    behavioral_cloning:
      demo_path: Assets\Demonstrations\near4
      strength: 0.7
      steps: 4000000
      curiosity:
        strength: 0.02
      gail:
        strength: 0.9
        gamma: 0.99
        encoding_size: 128
        demo_path: Assets\Demonstrations\near4
environment_parameters:
  time:
    curriculum:
      - name: Lesson0
        completion_criteria:
          measure: reward
          signal_smoothing: true
          min_lesson_length: 20
          behavior: Planner
          threshold: 1.0
        value: 14000
      - name: Lesson1
        completion_criteria:
          measure: reward
          signal_smoothing: true
          min_lesson_length: 20
          behavior: Planner
          threshold: 1.0
        value: 13800
      - name: Lesson2
        completion_criteria:
          measure: reward
          signal_smoothing: true
          min_lesson_length: 20
          behavior: Planner
          threshold: 1.0
        value: 13600
      - name: Lesson3
        completion_criteria:
          measure: reward
          signal_smoothing: true
          min_lesson_length: 20
          behavior: Planner
          threshold: 1.0
        value: 13400
      - name: Lesson4
        completion_criteria:
          measure: reward
          signal_smoothing: true
          min_lesson_length: 20
          behavior: Planner
          threshold: 1.0
        value: 13000