behaviors:
  RigidPlanner:
    trainer_type: ppo
    max_steps: 8000000
    time_horizon: 64
    summary_freq: 50000
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 5.0e-4
      beta: 5.0e-4
      epsilon: 0.25
      lambd: 0.95
      num_epoch: 3
    network_settings:
      hidden_units: 128
      memory_size: 256
      normalize: false
      num_layers: 5
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0